#!/bin/bash

if [ $# -eq 0 ]
    then echo "Wrong usage: Please provide argument - start/stop"
    exit 1
fi

if [ $1 == "start" ]
    then 
        echo "starting..."
        # check if von-network docker image has been built
        echo "starting von-network"
        ./von-network/manage start
        GENESIS=$(curl 0.0.0.0:9000/genesis)
        echo "starting aries-cloudagent-python"
        ./aries-cloudagent-python/script/run_docker start
        --inbound-transport http 0.0.0.0 8000 \
        --outbound-transport http
        --genesis-transactions $GENESIS
        --auto-respond-presentation-request
        --auto-accept-requests

fi

if [ $1 == "stop" ]
    then
        echo "stopping..."
        echo "stopping von-network"
        ./von-network/manage stop
fi